# Chap.07 実践編 線形回帰モデル（回帰）

## 7.9 プログラム実装

### Column Numpyを使ったコーディングテクニック

In [2]:
import numpy as np

ベクトル・ベクトル間の内積

$$
\begin{align*}
\mathbf{w} &= (w_1, w_2) \\
\mathbf{x} &= (x_1, x_2)
\end{align*}
$$

2つのベクトル間の内積

$$
y = \mathbf{w} \cdot \mathbf{x}
\\
y = w_1 x_1 + w_2 x_2
$$

In [3]:
# w = (1, 2)
w = np.array([1, 2])
print(w)
print(w.shape)

[1 2]
(2,)


In [4]:
# x = (3, 4)
x = np.array([3, 4])
print(x)
print(x.shape)

[3 4]
(2,)


In [5]:
# (3.7.2)式の内積の実装例
# y = w * x
# y = 1*3 + 2*4 = 11
y = x @ w
print(y)

11


行列・ベクトル間の内積

In [6]:
# X は3行2列の行列
X = np.array([[1, 2], [3, 4], [5, 6]])
print(X)
print(X.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [8]:
# w = (1, 2)
w = np.array([1, 2])
print(w)
print(w.shape)

[1 2]
(2,)


In [7]:
Y = X @ w
print(Y)
print(Y.shape)

[ 5 11 17]
(3,)


データ系列方向の行列・ベクトル間の内積

In [9]:
# X は3行2列の行列
X = np.array([[1, 2], [3, 4], [5, 6]])
print(X)
print(X.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [11]:
# 行列Xの転置行列の作成
XT = X.T
print(X)
print(XT)

[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [12]:
yd = np.array([1, 2, 3])
print(yd)

[1 2 3]


In [13]:
# 勾配値の計算(の一部)
grad = XT @ yd
print(grad)

[22 28]


In [14]:
# 損失関数値の計算
loss = np.mean(yd ** 2) / 2
loss

2.3333333333333335